EXECUTE BLOCK RETURNS (ID_PEDIDO INTEGER, DATE_REF DATE)

AS
DECLARE VARIABLE i INTEGER;
DECLARE VARIABLE num_days INTEGER;

BEGIN

  num_days = DATEDIFF(DAY, DATEADD(-EXTRACT(DAY FROM CURRENT_DATE) + 1 DAY TO CURRENT_DATE-1), 
  DATEADD(-1 DAY TO CURRENT_DATE));
  
  i = 0;
  WHILE (i <= num_days) DO
  BEGIN
    FOR 
    
      SELECT P.ID_PEDIDO, DATEADD(-:i DAY TO CURRENT_DATE) AS DATE_REF
      FROM PEDID P
      
      -- BLOCO PDRD TBFIS
      INNER JOIN (SELECT PRD.ID_PEDIDO,SUM(PDPUNITLIQUIDO*PDPQTDADE) AS VRVENDA FROM PDPRD PRD
      INNER JOIN (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR'))F ON PRD.FISCODIGO=F.FISCODIGO 
      GROUP BY 1
     )
      A ON P.ID_PEDIDO=A.ID_PEDIDO
      
      WHERE 
      PEDSITPED<>'C' AND
      
      PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE) AND
      
      -- ANTI JOIN 
      P.ID_PEDIDO NOT IN (
      
      
        SELECT P1.ID_PEDIDO
        FROM PEDID P1
        -- BLOCO PDRD TBFIS
      INNER JOIN (SELECT PRD1.ID_PEDIDO FROM PDPRD PRD1
      INNER JOIN (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR'))F1 ON PRD1.FISCODIGO=F1.FISCODIGO
      )
      A ON P1.ID_PEDIDO=A.ID_PEDIDO
      
        WHERE 
        PEDSITPED<>'C' AND
        PEDDTBAIXA BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
        AND PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
        
      )
      
      
    INTO :ID_PEDIDO, :DATE_REF
    DO
      SUSPEND;

    i = i + 1;
  END
END