EXECUTE BLOCK RETURNS (ID_PEDIDO INTEGER, DATE_REF DATE)
AS
DECLARE VARIABLE i INTEGER;
DECLARE VARIABLE num_days INTEGER;
BEGIN
  -- Calculate the number of days from the first of the month to yesterday
  num_days = DATEDIFF(DAY, DATEADD(-EXTRACT(DAY FROM CURRENT_DATE) + 1 DAY TO CURRENT_DATE-1), 
  DATEADD(-1 DAY TO CURRENT_DATE));
  
  i = 0;
  WHILE (i <= num_days) DO
  BEGIN
    FOR 
      SELECT ID_PEDIDO, DATEADD(-:i DAY TO CURRENT_DATE) AS DATE_REF
      FROM PEDID
      WHERE PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
      AND ID_PEDIDO NOT IN (
        SELECT ID_PEDIDO
        FROM PEDID
        WHERE PEDDTbaixa BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
        AND PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
      )
    INTO :ID_PEDIDO, :DATE_REF
    DO
      SUSPEND;

    i = i + 1;
  END
END
