EXECUTE BLOCK RETURNS (ID_PEDIDO INTEGER, DATE_REF DATE, PROCODIGO VARCHAR(100) )

AS
DECLARE VARIABLE i INTEGER;
DECLARE VARIABLE num_days INTEGER;

BEGIN

  num_days = DATEDIFF(DAY, DATEADD(-EXTRACT(DAY FROM CURRENT_DATE) + 1 DAY TO CURRENT_DATE-1), 
  DATEADD(-1 DAY TO CURRENT_DATE));
  
  i = 0;
  WHILE (i <= num_days) DO
  BEGIN
    FOR 
    
      SELECT P.ID_PEDIDO, DATEADD(-:i DAY TO CURRENT_DATE) AS DATE_REF,PROCODIGO
      FROM PEDID P
      LEFT JOIN (SELECT ID_PEDIDO,PROCODIGO FROM PDPRD)A ON P.ID_PEDIDO=A.ID_PEDIDO
      WHERE 
      PEDSITPED<>'C' AND
      
      PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE) AND
      
      -- ANTI JOIN 
      P.ID_PEDIDO NOT IN (
      
      
        SELECT ID_PEDIDO
        
        FROM PEDID
        
        WHERE 
        PEDSITPED<>'C' AND
        PEDDTBAIXA BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
        AND PEDDTEMIS BETWEEN '2024-03-01' AND DATEADD(-:i DAY TO CURRENT_DATE)
        
      )
    INTO :ID_PEDIDO, :DATE_REF, :PROCODIGO
    DO
      SUSPEND;

    i = i + 1;
  END
END