--- VALORES EMISSÃO POR TIPO

WITH FIS AS (
    SELECT FISCODIGO 
    FROM TBFIS 
    WHERE FISTPNATOP IN ('V','R','SR')
),
PED AS (
    SELECT 
        ID_PEDIDO,
        EMPCODIGO,
        TPCODIGO,
        PEDDTEMIS
    FROM PEDID P
    WHERE 
        (PEDDTEMIS BETWEEN (CURRENT_DATE) - EXTRACT(DAY FROM (CURRENT_DATE)) + 1 AND 'TODAY'
        OR PEDDTEMIS BETWEEN DATEADD(-1 YEAR TO (CURRENT_DATE) - EXTRACT(DAY FROM CURRENT_DATE) + 1)
        AND DATEADD(-1 YEAR TO (CURRENT_DATE) - EXTRACT(DAY FROM CURRENT_DATE) + 32 - EXTRACT(DAY FROM (CURRENT_DATE) - EXTRACT(DAY FROM (CURRENT_DATE)) + 32)))
        AND PEDSITPED <> 'C' 
        AND PEDLCFINANC IN ('S', 'L','N') 
        --AND TPCODIGO <> 13
),
PROD AS (
    SELECT PROCODIGO, IIF(PROCODIGO2 IS NULL, PROCODIGO, PROCODIGO2) CHAVE, PROTIPO 
    FROM PRODU 
    WHERE PROTIPO IN ('F','E')
)
SELECT 
    PD.EMPCODIGO,
    TRIM(REPLACE((SELECT EMPNOMEFNT FROM EMPRESA WHERE EMPCODIGO = PD.EMPCODIGO),'REPRO -','')) AS EMPRESA,
    PEDDTEMIS,
    CASE EXTRACT(WEEKDAY FROM PEDDTEMIS)
        WHEN 0 THEN 'DOM'
        WHEN 1 THEN 'SEG'
        WHEN 2 THEN 'TER'
        WHEN 3 THEN 'QUA'
        WHEN 4 THEN 'QUI'
        WHEN 5 THEN 'SEX'
        WHEN 6 THEN 'SAB'
    END AS DIA_SEMANA,
    EXTRACT(WEEK FROM PEDDTEMIS) AS WEEK_NUMBER,
    EXTRACT(YEAR FROM PEDDTEMIS) ANO,
   EXTRACT(MONTH FROM PEDDTEMIS)MES,
    P.TPCODIGO,
    TPDESCRICAO,
    CASE 
        WHEN P.TPCODIGO IN (6) THEN 'ATACADÃO'
        WHEN P.TPCODIGO IN (11) AND LEFT(CHAVE,2) IN ('LA','LS') THEN 'ATACADO 11 LA'
        WHEN P.TPCODIGO IN (11) AND LEFT(CHAVE,2) NOT IN ('LA','LS') THEN 'ATACADO 11 BLOCO'
        WHEN P.TPCODIGO IN (15) THEN 'ATACADO 15' 
        WHEN P.TPCODIGO IN (1)  AND LEFT(CHAVE,2) IN ('LA','LS') THEN 'ATACADO 1 LA'
        WHEN P.TPCODIGO IN (1)  AND LEFT(CHAVE,2) NOT IN ('LA','LS') THEN 'ATACADO 1 BLOCO' 
        WHEN P.TPCODIGO IN (12) AND LEFT(CHAVE,2) IN ('LA','LS') THEN '12 LA'
        WHEN P.TPCODIGO IN (12) AND LEFT(CHAVE,2) NOT IN ('LA','LS') THEN '12 SURF' 
        WHEN P.TPCODIGO IN (2, 7, 14) AND LEFT(CHAVE,2) NOT IN ('LA','LS') THEN '2 + 7 + 14'
        WHEN P.TPCODIGO IN (3,10) AND LEFT(CHAVE,2) IN ('LA','LS') THEN '3 + 10'
        WHEN P.TPCODIGO IN (5) THEN 'SERVICO'
        ELSE 'OUTROS' 
    END AS TIPO_PEDIDOS,
    IIF(PR.PROCODIGO IS NOT NULL, 1, 0) AS LENTES, 
    LEFT(CHAVE,2) AS CHAVE,
    COUNT(DISTINCT PD.ID_PEDIDO) AS QTD_PEDIDOS,
    SUM(PDPQTDADE) AS QTD,
    SUM(PDPUNITLIQUIDO*PDPQTDADE) AS VRVENDA
FROM 
    PDPRD PD
INNER JOIN 
    PED P ON PD.ID_PEDIDO = P.ID_PEDIDO
INNER JOIN 
    FIS F ON PD.FISCODIGO = F.FISCODIGO
LEFT JOIN 
    TPPEDID TP ON P.TPCODIGO = TP.TPCODIGO
LEFT JOIN 
    PROD PR ON PR.PROCODIGO = PD.PROCODIGO 
GROUP BY 
    1,2,3,4,5,6,7,8,9,10,11,12

        
  -- ATACADO= ATACADO 11 LA  ,ATACADO 11 BLOCO , ATACADO 15 ,ATACADO 1 LA,ATACADO 1 BLOCO
  -- LENTES PRONTAS = ATACADO 11 LA,ATACADO 15,ATACADO 1 LA,  12 LA, 3 + 10
  -- ATACADÃO
  -- LENTES SURFAÇADAS = 12 SURF , 2 + 7 + 14
  